# ado-import.ps1 — generated by cross-06-ado-project-onboard skill
# Review ado-artifacts.json before running.
# Usage: $env:ADO_PAT = "<pat>"; .\ado-import.ps1
# Add -DryRun to preview without creating anything in ADO.
param([switch]$DryRun)
$sharedScript = "C:\AICOE\eva-foundation\38-ado-poc\scripts\ado-import-project.ps1"
if (-not (Test-Path $sharedScript)) { throw "Shared import script not found: $sharedScript" }
& $sharedScript -ArtifactsFile (Join-Path $PSScriptRoot "ado-artifacts.json") -DryRun:$DryRun
